
name: Raysect - compile and test

on:
  push:
    paths-ignore:
    - ".github/control/prepareForPullRequest.txt"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Download repository
      uses: actions/checkout@v2

    - name: Install software packages
      run: |
        export PERL_MM_USE_DEFAULT=1
        sudo cpan install Data::Table::Text GitHub::Crud Data::Dump 1>/dev/null
        pip install numpy scipy matplotlib cython>=0.28
        
    - name: Build Raysect
      run: |
        export PERL_MM_USE_DEFAULT=1
        dev/build.sh
    
    
    - name: Run tests
      run: |
        dev/test.sh
        
    - name: Upload results
      env:
         token: ${{ secrets.GITHUB_TOKEN }}
      run: |
        tree
        #perl github/uploadOut.pl $GITHUB_REPOSITORY docs/ docs/  $token
        #perl github/uploadOut.pl $GITHUB_REPOSITORY out/   out/  $token        
        
