
name: Raysect tests

on:
  push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Download repository
      uses: actions/checkout@v2

    - name: Install software packages
      run: |
        pip install numpy scipy matplotlib cython>=0.28
        dev/build.sh
    - name: Run tests
      run: |
        script: dev/test.sh
